# Generated by Django 4.0.4 on 2022-08-02 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_student_enrollment_no_alter_student_scholar_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclassroom',
            name='uid',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
