# Generated by Django 4.0.4 on 2022-08-10 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='students',
        ),
    ]
